sudo: true
os: linux
language: python

python:
    - "3.5"
env:
- ASSIGNMENT_REPO=https://github.com/apoorvsemwal/BigdataAnalytics.git PYTHONHASHSEED=0 PYTHONPATH=$PYTHONPATH:$PWD/answers JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - pip install pyspark pytest

script:
 - pytest tests

after_success:
  - echo "success"

after_failure:
  - echo "failure"
